### ISSUE TITLE
Need support for Rails 5

### ISSUE THREAD

**Issue by NullVoxPopuli** [luisalima/outdatedbrowser_rails#9]
```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.0.1)

    outdatedbrowser_rails was resolved to 1.0.2.0, which depends on
      rails (>= 3.2.16, ~> 3.2)
```

ya should just be able to remove the version dependency in the gemspec, and cut a new release, yeah?

**Comment by luisalima** [comment]
@NullVoxPopuli Thanks for the issue! I'm completely swamped with work right now, feel free to make a PR and I'll merge it 👍

**Comment by luisalima** [comment]
Closed in https://github.com/luisalima/outdatedbrowser_rails/pull/10
